
def distinctpower(a,b):
    '''Returns the number of distinct intergers that are generated by the experssion i**j where 2 <= i <= a and 2 <= j <= b'''
    powers = []
    for i in range(2,a+1):
        for j in range(2,b+1):
            powers.append(i**j)
    powers = list(set(powers))
    return(len(powers))
